name: Python application

on:
  push:
   branches: [ master ]
  pull_request:
    branches: [ master ] 
       
jobs: 
  build:
 
    runs-on: ubuntu-latest
 
    steps:
    - uses: actions/checkout@v1
    - name: Build & Push Image
      run: |
        #Adding Secrets below
        docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }} 
        docker image build -t leoftw/flaskrepopython:latest .
        docker push leoftw/flaskrepopython:latest